import type { PageComponentDef, PageComponentType } from "../../utils/pageDef";
import { COMPONENT_SPECS } from "../../reference/component-reference-data";

/** Short random hex (4 chars) for autogenerated ids, e.g. "0da1". */
function shortId(): string {
  return Math.random().toString(16).slice(2, 6);
}

/** Autogenerated id: type lowercase + short hex, e.g. "number0da1", "texta3f2". */
export function generateComponentId(type: PageComponentType): string {
  return `${type.toLowerCase()}${shortId()}`;
}

/** Return default PageComponentDef for a given type (id autogenerated as type + shortId). */
export function getDefaultComponentDef(type: PageComponentType): PageComponentDef {
  const spec = COMPONENT_SPECS.find((s) => s.type === type);
  const example = spec ? (spec.exampleJson as Record<string, unknown>) : {};
  return {
    ...example,
    id: generateComponentId(type),
    type,
    label: example.label ?? type,
  } as PageComponentDef;
}

export const COMPONENT_TYPES = COMPONENT_SPECS.map((s) => s.type);
