import type { PageComponentDef, PageComponentType } from "../../utils/pageDef";
import { COMPONENT_SPECS, PALETTE_SPECS } from "../../reference/component-reference-data";

/** Short random hex (4 chars) for autogenerated ids, e.g. "0da1". */
function shortId(): string {
  return Math.random().toString(16).slice(2, 6);
}

/** Autogenerated id: type lowercase + short hex, e.g. "number0da1", "texta3f2". */
export function generateComponentId(type: PageComponentType): string {
  return `${type.toLowerCase()}${shortId()}`;
}

/** Resolve palette id (e.g. "TextField") to concrete PageComponentType (e.g. "text"). */
function resolveToConcreteType(paletteIdOrType: string): PageComponentType | null {
  const palette = PALETTE_SPECS.find((p) => p.id === paletteIdOrType);
  if (palette) return palette.defaultType as PageComponentType;
  if (COMPONENT_SPECS.some((s) => s.type === paletteIdOrType)) return paletteIdOrType as PageComponentType;
  return null;
}

/** Return default PageComponentDef for a palette id (e.g. "TextField") or concrete type (e.g. "text"). */
export function getDefaultComponentDef(paletteIdOrType: string): PageComponentDef | null {
  const type = resolveToConcreteType(paletteIdOrType);
  if (!type) return null;
  const spec = COMPONENT_SPECS.find((s) => s.type === type);
  const example = spec ? (spec.exampleJson as Record<string, unknown>) : {};
  return {
    ...example,
    id: generateComponentId(type),
    type,
    label: spec?.defaultLabel ?? (example.label as string) ?? type,
  } as PageComponentDef;
}

/** Palette ids + concrete types that are valid for drag-from-palette. */
export const VALID_PALETTE_DROP_IDS = [
  ...PALETTE_SPECS.map((p) => p.id),
  ...COMPONENT_SPECS.map((s) => s.type),
];

export const COMPONENT_TYPES = COMPONENT_SPECS.map((s) => s.type);
